### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by JFGHT** [JFGHT/Classic-Bot#5]
- [x] Investigate and fix specific crash when user leaves.
- [ ] Display menu with kick, ban, whisper functionalities in channel user list when clicking over an user.
- [ ] Play sound when whisper and conversation is not focused and when mentioned.
- [ ] Remove users.jsx component.
- [ ] Refactor px to rem in all css files.
- [ ] Display number of unread messages per conversation / channel.
- [ ] Create changelog file.
- [ ] Transition between components.
- [ ] Tests.
